import type Transaction from '~/features/transactions/types/transaction';

export const MOCK_TRANSACTIONS: Transaction[] = [
    {
        id: 'tx1',
        userId: 'mock-user',
        mode: 'expense',
        amount: 185,
        note: '星巴克咖啡星巴克咖啡星巴克咖啡',
        date: '2025-10-01',
        categoryId: 'food',
        templateId: null,
        createdAt: Date.now() - 1000 * 60 * 60 * 24,
    },
    {
        id: 'tx2',
        userId: 'mock-user',
        mode: 'expense',
        amount: 30,
        note: '捷運通勤',
        date: '2025-10-02',
        categoryId: 'commute',
        templateId: 't1',
        createdAt: Date.now() - 1000 * 60 * 60 * 20,
    },
    {
        id: 'tx3',
        userId: 'mock-user',
        mode: 'income',
        amount: 80000,
        note: '月薪',
        date: '2025-11-10',
        categoryId: 'saving',
        templateId: null,
        createdAt: Date.now() - 1000 * 60 * 60 * 48,
    },
    {
        id: 'tx4',
        userId: 'mock-user',
        mode: 'income',
        amount: 71000,
        note: '月薪',
        date: '2025-08-10',
        categoryId: 'saving',
        templateId: null,
        createdAt: Date.now() - 1000 * 60 * 60 * 48,
    },
    {
        id: 'tx5',
        userId: 'mock-user',
        mode: 'income',
        amount: 75000,
        note: '月薪',
        date: '2025-09-10',
        categoryId: 'saving',
        templateId: null,
        createdAt: Date.now() - 1000 * 60 * 60 * 48,
    },
    {
        id: 'tx61',
        userId: 'mock-user',
        mode: 'expense',
        amount: 60,
        note: '飲料',
        date: '2025-11-22',
        categoryId: 'food',
        templateId: null,
        createdAt: Date.now() - 1000 * 60 * 60 * 24,
    },
    {
        id: 'tx7',
        userId: 'mock-user',
        mode: 'expense',
        amount: 1200,
        note: 'TPA卡自動加值',
        date: '2025-10-03',
        categoryId: 'commute',
        templateId: 't1',
        createdAt: Date.now() - 1000 * 60 * 60 * 20,
    },
];
